apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: server-inventory
type: Opaque
stringData:
  POSTGRES_USER: "your-db-user"
  POSTGRES_PASSWORD: "your-db-password"
  POSTGRES_DB: "app_db"