apiVersion: v1
kind: Service
metadata:
  name: server-inventory-api
  namespace: server-inventory
spec:
  selector:
    app: server-inventory-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP